### ISSUE TITLE
ros2_control and ros2_controllers foxy release not correctly with rosinstall_generator and vcs (Windows)

### ISSUE THREAD

**Issue by BenjaminHug8** [ros2-gbp/ros2_control-release#1]
Hi,

By running the following commands on Windows 10 with Foxy:
```
pip install rosinstall_generator
rosinstall_generator ros2_control ros2_controllers angles --rosdistro foxy > deps.repos
vcs import src < deps.repos
```

The package `ros2_control` and `ros2_controllers` are downloaded but unfortunately they are almost empty (except `.git`, `CHANGELOG.rst`, `CMakeLists.txt` and `packages.xml`.

Inside the `deps.repos` file:
```
- git:
    local-name: ros2_control/ros2_control
    uri: https://github.com/ros2-gbp/ros2_control-release.git
    version: release/foxy/ros2_control/0.8.0-1
- git:
    local-name: ros2_controllers/ros2_controllers
    uri: https://github.com/ros2-gbp/ros2_controllers-release.git
    version: release/foxy/ros2_controllers/0.5.0-1
```

`angles` package is correctly imported.

Could you tell me if I simply made a mistake or if it is indeed an issue ?

Thanks in advance,
Benjamin
